//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webClientTestForm.WebServiceSample {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetWeatherRequest", Namespace="http://www.52uyou.com/")]
    [System.SerializableAttribute()]
    public partial class GetWeatherRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        private webClientTestForm.WebServiceSample.TemperatureType TemperatureTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClientTestForm.WebServiceSample.TemperatureType TemperatureType {
            get {
                return this.TemperatureTypeField;
            }
            set {
                if ((this.TemperatureTypeField.Equals(value) != true)) {
                    this.TemperatureTypeField = value;
                    this.RaisePropertyChanged("TemperatureType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemperatureType", Namespace="http://www.52uyou.com/")]
    public enum TemperatureType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fahrenheit = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Celsius = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetWeatherRespose", Namespace="http://www.52uyou.com/")]
    [System.SerializableAttribute()]
    public partial class GetWeatherRespose : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private webClientTestForm.WebServiceSample.TemperatureCondition ConditionField;
        
        private int TemperatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClientTestForm.WebServiceSample.TemperatureCondition Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((this.ConditionField.Equals(value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Temperature {
            get {
                return this.TemperatureField;
            }
            set {
                if ((this.TemperatureField.Equals(value) != true)) {
                    this.TemperatureField = value;
                    this.RaisePropertyChanged("Temperature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemperatureCondition", Namespace="http://www.52uyou.com/")]
    public enum TemperatureCondition : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rainy = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sunny = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cloudy = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thunderstorm = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.52uyou.com/", ConfigurationName="WebServiceSample.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://www.52uyou.com/ 的元素名称 req 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.52uyou.com/GetWeather", ReplyAction="*")]
        webClientTestForm.WebServiceSample.GetWeatherResponse GetWeather(webClientTestForm.WebServiceSample.GetWeatherRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.52uyou.com/GetWeather", ReplyAction="*")]
        System.IAsyncResult BeginGetWeather(webClientTestForm.WebServiceSample.GetWeatherRequest1 request, System.AsyncCallback callback, object asyncState);
        
        webClientTestForm.WebServiceSample.GetWeatherResponse EndGetWeather(System.IAsyncResult result);
        
        // CODEGEN: 命名空间 http://www.52uyou.com/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.52uyou.com/HelloWorld", ReplyAction="*")]
        webClientTestForm.WebServiceSample.HelloWorldResponse HelloWorld(webClientTestForm.WebServiceSample.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.52uyou.com/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(webClientTestForm.WebServiceSample.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        webClientTestForm.WebServiceSample.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        // CODEGEN: 命名空间 http://www.52uyou.com/ 的元素名称 message 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.52uyou.com/ReverseString", ReplyAction="*")]
        webClientTestForm.WebServiceSample.ReverseStringResponse ReverseString(webClientTestForm.WebServiceSample.ReverseStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.52uyou.com/ReverseString", ReplyAction="*")]
        System.IAsyncResult BeginReverseString(webClientTestForm.WebServiceSample.ReverseStringRequest request, System.AsyncCallback callback, object asyncState);
        
        webClientTestForm.WebServiceSample.ReverseStringResponse EndReverseString(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeather", Namespace="http://www.52uyou.com/", Order=0)]
        public webClientTestForm.WebServiceSample.GetWeatherRequest1Body Body;
        
        public GetWeatherRequest1() {
        }
        
        public GetWeatherRequest1(webClientTestForm.WebServiceSample.GetWeatherRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.52uyou.com/")]
    public partial class GetWeatherRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webClientTestForm.WebServiceSample.GetWeatherRequest req;
        
        public GetWeatherRequest1Body() {
        }
        
        public GetWeatherRequest1Body(webClientTestForm.WebServiceSample.GetWeatherRequest req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeatherResponse", Namespace="http://www.52uyou.com/", Order=0)]
        public webClientTestForm.WebServiceSample.GetWeatherResponseBody Body;
        
        public GetWeatherResponse() {
        }
        
        public GetWeatherResponse(webClientTestForm.WebServiceSample.GetWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.52uyou.com/")]
    public partial class GetWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webClientTestForm.WebServiceSample.GetWeatherRespose GetWeatherResult;
        
        public GetWeatherResponseBody() {
        }
        
        public GetWeatherResponseBody(webClientTestForm.WebServiceSample.GetWeatherRespose GetWeatherResult) {
            this.GetWeatherResult = GetWeatherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://www.52uyou.com/", Order=0)]
        public webClientTestForm.WebServiceSample.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(webClientTestForm.WebServiceSample.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://www.52uyou.com/", Order=0)]
        public webClientTestForm.WebServiceSample.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(webClientTestForm.WebServiceSample.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.52uyou.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseString", Namespace="http://www.52uyou.com/", Order=0)]
        public webClientTestForm.WebServiceSample.ReverseStringRequestBody Body;
        
        public ReverseStringRequest() {
        }
        
        public ReverseStringRequest(webClientTestForm.WebServiceSample.ReverseStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.52uyou.com/")]
    public partial class ReverseStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        public ReverseStringRequestBody() {
        }
        
        public ReverseStringRequestBody(string message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseStringResponse", Namespace="http://www.52uyou.com/", Order=0)]
        public webClientTestForm.WebServiceSample.ReverseStringResponseBody Body;
        
        public ReverseStringResponse() {
        }
        
        public ReverseStringResponse(webClientTestForm.WebServiceSample.ReverseStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.52uyou.com/")]
    public partial class ReverseStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReverseStringResult;
        
        public ReverseStringResponseBody() {
        }
        
        public ReverseStringResponseBody(string ReverseStringResult) {
            this.ReverseStringResult = ReverseStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : webClientTestForm.WebServiceSample.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWeatherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWeatherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public webClientTestForm.WebServiceSample.GetWeatherRespose Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((webClientTestForm.WebServiceSample.GetWeatherRespose)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReverseStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReverseStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<webClientTestForm.WebServiceSample.WebService1Soap>, webClientTestForm.WebServiceSample.WebService1Soap {
        
        private BeginOperationDelegate onBeginGetWeatherDelegate;
        
        private EndOperationDelegate onEndGetWeatherDelegate;
        
        private System.Threading.SendOrPostCallback onGetWeatherCompletedDelegate;
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginReverseStringDelegate;
        
        private EndOperationDelegate onEndReverseStringDelegate;
        
        private System.Threading.SendOrPostCallback onReverseStringCompletedDelegate;
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetWeatherCompletedEventArgs> GetWeatherCompleted;
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<ReverseStringCompletedEventArgs> ReverseStringCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webClientTestForm.WebServiceSample.GetWeatherResponse webClientTestForm.WebServiceSample.WebService1Soap.GetWeather(webClientTestForm.WebServiceSample.GetWeatherRequest1 request) {
            return base.Channel.GetWeather(request);
        }
        
        public webClientTestForm.WebServiceSample.GetWeatherRespose GetWeather(webClientTestForm.WebServiceSample.GetWeatherRequest req) {
            webClientTestForm.WebServiceSample.GetWeatherRequest1 inValue = new webClientTestForm.WebServiceSample.GetWeatherRequest1();
            inValue.Body = new webClientTestForm.WebServiceSample.GetWeatherRequest1Body();
            inValue.Body.req = req;
            webClientTestForm.WebServiceSample.GetWeatherResponse retVal = ((webClientTestForm.WebServiceSample.WebService1Soap)(this)).GetWeather(inValue);
            return retVal.Body.GetWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult webClientTestForm.WebServiceSample.WebService1Soap.BeginGetWeather(webClientTestForm.WebServiceSample.GetWeatherRequest1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWeather(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetWeather(webClientTestForm.WebServiceSample.GetWeatherRequest req, System.AsyncCallback callback, object asyncState) {
            webClientTestForm.WebServiceSample.GetWeatherRequest1 inValue = new webClientTestForm.WebServiceSample.GetWeatherRequest1();
            inValue.Body = new webClientTestForm.WebServiceSample.GetWeatherRequest1Body();
            inValue.Body.req = req;
            return ((webClientTestForm.WebServiceSample.WebService1Soap)(this)).BeginGetWeather(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webClientTestForm.WebServiceSample.GetWeatherResponse webClientTestForm.WebServiceSample.WebService1Soap.EndGetWeather(System.IAsyncResult result) {
            return base.Channel.EndGetWeather(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public webClientTestForm.WebServiceSample.GetWeatherRespose EndGetWeather(System.IAsyncResult result) {
            webClientTestForm.WebServiceSample.GetWeatherResponse retVal = ((webClientTestForm.WebServiceSample.WebService1Soap)(this)).EndGetWeather(result);
            return retVal.Body.GetWeatherResult;
        }
        
        private System.IAsyncResult OnBeginGetWeather(object[] inValues, System.AsyncCallback callback, object asyncState) {
            webClientTestForm.WebServiceSample.GetWeatherRequest req = ((webClientTestForm.WebServiceSample.GetWeatherRequest)(inValues[0]));
            return this.BeginGetWeather(req, callback, asyncState);
        }
        
        private object[] OnEndGetWeather(System.IAsyncResult result) {
            webClientTestForm.WebServiceSample.GetWeatherRespose retVal = this.EndGetWeather(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWeatherCompleted(object state) {
            if ((this.GetWeatherCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWeatherCompleted(this, new GetWeatherCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWeatherAsync(webClientTestForm.WebServiceSample.GetWeatherRequest req) {
            this.GetWeatherAsync(req, null);
        }
        
        public void GetWeatherAsync(webClientTestForm.WebServiceSample.GetWeatherRequest req, object userState) {
            if ((this.onBeginGetWeatherDelegate == null)) {
                this.onBeginGetWeatherDelegate = new BeginOperationDelegate(this.OnBeginGetWeather);
            }
            if ((this.onEndGetWeatherDelegate == null)) {
                this.onEndGetWeatherDelegate = new EndOperationDelegate(this.OnEndGetWeather);
            }
            if ((this.onGetWeatherCompletedDelegate == null)) {
                this.onGetWeatherCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWeatherCompleted);
            }
            base.InvokeAsync(this.onBeginGetWeatherDelegate, new object[] {
                        req}, this.onEndGetWeatherDelegate, this.onGetWeatherCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webClientTestForm.WebServiceSample.HelloWorldResponse webClientTestForm.WebServiceSample.WebService1Soap.HelloWorld(webClientTestForm.WebServiceSample.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            webClientTestForm.WebServiceSample.HelloWorldRequest inValue = new webClientTestForm.WebServiceSample.HelloWorldRequest();
            inValue.Body = new webClientTestForm.WebServiceSample.HelloWorldRequestBody();
            webClientTestForm.WebServiceSample.HelloWorldResponse retVal = ((webClientTestForm.WebServiceSample.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult webClientTestForm.WebServiceSample.WebService1Soap.BeginHelloWorld(webClientTestForm.WebServiceSample.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            webClientTestForm.WebServiceSample.HelloWorldRequest inValue = new webClientTestForm.WebServiceSample.HelloWorldRequest();
            inValue.Body = new webClientTestForm.WebServiceSample.HelloWorldRequestBody();
            return ((webClientTestForm.WebServiceSample.WebService1Soap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webClientTestForm.WebServiceSample.HelloWorldResponse webClientTestForm.WebServiceSample.WebService1Soap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHelloWorld(System.IAsyncResult result) {
            webClientTestForm.WebServiceSample.HelloWorldResponse retVal = ((webClientTestForm.WebServiceSample.WebService1Soap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webClientTestForm.WebServiceSample.ReverseStringResponse webClientTestForm.WebServiceSample.WebService1Soap.ReverseString(webClientTestForm.WebServiceSample.ReverseStringRequest request) {
            return base.Channel.ReverseString(request);
        }
        
        public string ReverseString(string message) {
            webClientTestForm.WebServiceSample.ReverseStringRequest inValue = new webClientTestForm.WebServiceSample.ReverseStringRequest();
            inValue.Body = new webClientTestForm.WebServiceSample.ReverseStringRequestBody();
            inValue.Body.message = message;
            webClientTestForm.WebServiceSample.ReverseStringResponse retVal = ((webClientTestForm.WebServiceSample.WebService1Soap)(this)).ReverseString(inValue);
            return retVal.Body.ReverseStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult webClientTestForm.WebServiceSample.WebService1Soap.BeginReverseString(webClientTestForm.WebServiceSample.ReverseStringRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReverseString(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReverseString(string message, System.AsyncCallback callback, object asyncState) {
            webClientTestForm.WebServiceSample.ReverseStringRequest inValue = new webClientTestForm.WebServiceSample.ReverseStringRequest();
            inValue.Body = new webClientTestForm.WebServiceSample.ReverseStringRequestBody();
            inValue.Body.message = message;
            return ((webClientTestForm.WebServiceSample.WebService1Soap)(this)).BeginReverseString(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webClientTestForm.WebServiceSample.ReverseStringResponse webClientTestForm.WebServiceSample.WebService1Soap.EndReverseString(System.IAsyncResult result) {
            return base.Channel.EndReverseString(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndReverseString(System.IAsyncResult result) {
            webClientTestForm.WebServiceSample.ReverseStringResponse retVal = ((webClientTestForm.WebServiceSample.WebService1Soap)(this)).EndReverseString(result);
            return retVal.Body.ReverseStringResult;
        }
        
        private System.IAsyncResult OnBeginReverseString(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string message = ((string)(inValues[0]));
            return this.BeginReverseString(message, callback, asyncState);
        }
        
        private object[] OnEndReverseString(System.IAsyncResult result) {
            string retVal = this.EndReverseString(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReverseStringCompleted(object state) {
            if ((this.ReverseStringCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReverseStringCompleted(this, new ReverseStringCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReverseStringAsync(string message) {
            this.ReverseStringAsync(message, null);
        }
        
        public void ReverseStringAsync(string message, object userState) {
            if ((this.onBeginReverseStringDelegate == null)) {
                this.onBeginReverseStringDelegate = new BeginOperationDelegate(this.OnBeginReverseString);
            }
            if ((this.onEndReverseStringDelegate == null)) {
                this.onEndReverseStringDelegate = new EndOperationDelegate(this.OnEndReverseString);
            }
            if ((this.onReverseStringCompletedDelegate == null)) {
                this.onReverseStringCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReverseStringCompleted);
            }
            base.InvokeAsync(this.onBeginReverseStringDelegate, new object[] {
                        message}, this.onEndReverseStringDelegate, this.onReverseStringCompletedDelegate, userState);
        }
    }
}
